sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - git config --global user.name 'Travis-CI'
  - git config --global user.email 'dummy@example.org'
after_script: NODE_ENV=test grunt sendCoverallsInfo
env:
  global:
    - secure: wTtm1sVNFjsAWDHSRBniva4fBblSBFsmpMRzTwijE229TtUQSBP3S23cj3PcpxjbcI1d067BYXPOUVCzrvrjP8ZkA/rUF03vQpVX0SCXnjO1jeAfDcEW99HQooW7z7B4YLkdBvZ3Tdbfi/8ZfSLKZ5+s9ctJ5DALzY4ChSZGTiAa7Te7bBAZit2rqjkGFeDe3/auQ0W8jAha3Oia2BHdB37PgfEUbbj7QNY8BEdaj8cncCz/ki5+FQdA+EdPT/xMBDWjen2eh6LItjgxZifDMiF0D8GFkifSm/Zk2N+Wffyr+CYu8/tMtKTobhd7UXWipBSbpqhTLsnsdBuSZd46QJo7mrTLxsFyjrY5yyUrRBtMhzuo5lqt6D46bvbnInHVCTSWkjLwK3xcTsYhmdPw3ebCLsXaAqXPDtSakiGViUnzG70V+V7u6mw7rVA3e1GjDo2qg4mjVE8YPSPBvdrYWP9dU2xz7vSnEJZzQuy3zmK6nKI13JFEfj6Lx5LPXtBcpR79nhxA5+sLUc3JZxcfNKUcwX0NBfQ7c2oa/NEU6C+fodkYq8dmBJLGSnDU4HfMxSRaCux3H9DNGISUNphbXfG+eZAX1xpxuH1S9s5qDj2Xcp/4uSuYT8H1bwCG+je/RSB4qsM2XpMdloACF5+O+pB6lnnOaFoFlWAHteY/+wc=
